### ISSUE TITLE
Consider YAML or JSON option for .command files

### ISSUE THREAD

**Issue by johnecobo** [Stub-O-Matic/stubo-app#12]
At present Stubo command files consist of multiple lines of REST calls to Stubo. This is good, simple and demonstrates the REST API.

However, these days it has become more normal to use YML or JSON for such command files. Doing so might decrease the Stubo learning curve for new adopters.

**Comment by erowan** [comment]
The structure of the command file will need to be extended to support the new REST matching in #7. Currently the extra info provided after the api call specifies the matcher/s & response file for put/stub and the request file to use for get/response calls. This needs extending to 

1) put/stub should point to a JSON stub def
2) get/response should point to a JSON request def

Whether the commands file is a line delimited text file or JSON doesn't concern me too much however. The commands file is run through Torando template before execution.

**Comment by johnecobo** [comment]
Whatever is decided, it must be backwards compatible and not require changes to existing command files.

**Comment by erowan** [comment]
Yes YML looks the best choice to support the rest extensions. The existing commands file still needs to be supported on import. I don't believe we need to support exporting it anymore?

**Comment by johnecobo** [comment]
Next step would be to show an example YAML command file, we'll share with users and confirm there would be no need to export the current style.

**Comment by erowan** [comment]
How about this? It shows JSON payloads defined in YAML. The stub for recording can be an external reference using the 'file' key which includes URIs or inline using the 'json' key. Requests for playbacks use the same convention. Note this is a simplified syntax from the existing text commands file. You can only specify recording (put/stub) and playbacks (get/response) calls. Recordings and Playbacks will be enclosed within a begin/end session using the provided session but the user doesn't have to explicitly specify this. Additionally the recording will also include an initial delete/stubs call when executed.

```javascript
# Stubo YAML

# Describe your stubs here       
recording:
  scenario: rest
  session:  rest_recording
  stubs: 
    - 
     file: stub1.json
     vars:
        recorded_at : "{{as_date('2015-01-10')}}" 
    - 
     json: {
           "request": {
               "method": "GET",
               "bodyPatterns": [
                   {
                     "jsonpath" : ["cmd.x"]
                   }
               ],
               "headers" : {
                  "Content-Type" : "application/json",
                  "X-Custom-Header" : "1234"
               }
           },
           "response": {
               "status": 200,
               "body": "{\"version\": \"1.2.3\", \"data\": {\"status\": \"all ok 2\"}}",
                "headers" : {
                  "Content-Type" : "application/json",
                  "X-Custom-Header" : "1234"
               }
           }
         }
     vars:
        foo: bar

# Provide your requests here          
playback:
  scenario: rest
  session:  rest_playback
  requests:
    -
      file: request1.json
      vars:
         played_at : "{{as_date('2015-01-20')}}"
    -     
      json: {"cmd": {"x": "y"}}
      vars:
         played_at : "{{as_date('2015-01-20')}}"    
```

**Comment by johnecobo** [comment]
Looks pretty good.
1. please specify the defaults, for example, I assume one need not write out that a response has status of 200 every time.
2. do you really need the "\"s in :  "body": "{\"version\": \"1.2.3\", \"data\": {\"status\": \"all ok 2\"}}",  ?
3. any magic calls to begin or end sessions need to fail if the scenario already has an active session of that name. We can't have one user killing another's session.

**Comment by erowan** [comment]
The defaults are request.method = "POST" & response.status = 200
The json payload in the request & response body content are strings so the the inner strings need escaping. Potentially this YAML file could be a generated if we provide some front end tooling.

**Comment by erowan** [comment]
Another thing to note is template processing. Template variables or expressions within need to be escaped with a surrounding {}. It also won't be easy to support template flow control directives such as for, if etc. Do we need to?

 vars:
         played_at : "{{as_date('2015-01-20')}}"

**Comment by johnecobo** [comment]
Can you load the YAML, then process it to turn the body into strings? Users will not like the escaping.

**Comment by johnecobo** [comment]
We have never had flow control in command files, but I have had situations when I thought it would be nice. Look at Google jasonnet and see if that might help.

**Comment by erowan** [comment]
yes we do here is an example: 

https://github.com/Stub-O-Matic/stubo-app/blob/master/stubo/static/cmds/perf/perf_setup.commands#L16

**Comment by erowan** [comment]
Yes I should be able to convert the body into strings if they are specified as json in the file.

**Comment by johnecobo** [comment]
Regarding perf_setup.commands#L16, you are quite right, Stubo DOES support flow control in command files. I've never seen end users using it.

**Comment by erowan** [comment]
finished with https://github.com/Stub-O-Matic/stubo-app/commit/5f440d2fb9303c490a71ad71fd7fc02db8ae6702
