### ISSUE TITLE
Tracker page only showing a few records

### ISSUE THREAD

**Issue by twinser** [Stub-O-Matic/stubo-app#14]
On 0.6.0, the tracker page seems to only be showing a few records on page 1, even if you go forward to page 2 and come back. It was showing two, but switched full tracking off then on and it now shows four:

![image](https://cloud.githubusercontent.com/assets/6523398/6573617/8e40847c-c714-11e4-9b2d-de2a070f6de2.png)

**Comment by erowan** [comment]
closed with 2f9cacd

**Comment by twinser** [comment]
It's back! 

![image](https://cloud.githubusercontent.com/assets/6523398/6825263/29b57308-d2f1-11e4-8f52-60eef8dad2d5.png)

**Comment by twinser** [comment]
I think I should be able to code a fix, will have a go and submit a pull

**Comment by twinser** [comment]
Closed with 1246ef0
