### ISSUE TITLE
Allow parameter overrides when uploading stubs (POST /stubo/default/execCmds)

### ISSUE THREAD

**Issue by sponte** [Stub-O-Matic/stubo-app#39]
We found a need to be able to override scenario parameter when uploading stubs to stubo server. Currently when we record and export the stubs, command file contains following lines:

```
delete/stubs?scenario=MyScenario
begin/session?scenario=MyScenario&session=MySession&mode=record
put/stub?session=MySession&stub_created_date=2012-12-05&ext_module=testModule&stubbedSystemDate=2012-09-26,MyScenario_33314.textMatcher,MyScenario_33315.textMatcher,MyScenario_27309.response
end/session?session=MySession
# end of record for scenario
```

It would be good if we could provide a list of overrides through /stubo/default/execCmds request, for instance:

```
POST /stubo/default/execCmds HTTP/1.1
User-Agent: Stubo Client v1.0
Host: xxxxxxxxx:1234
Content-Length: xxxx
Content-Type: application/x-www-form-urlencoded

cmdFile=https%3A%2F%2Fmy-repository.com%2Fstubs%2FMyScenario.jar%26commandParameterOverrides=%7B%22scenario%22%3A%22MyDynamicScenario%22%2C%22session%22%3A%22MyOverridenSession%22%7D
```

commandParameterOverrides is a JSON structure:
```json
{
   "scenario": "MyDynamicScenario",
   "session": "MyOverridenSession"
}
```

Stubo would then interrogate commandParameterOverrides while executing commands and override parameters if it finds a match.

**Comment by johnecobo** [comment]
Stubo is part way there, see http://stubo-app.readthedocs.org/en/latest/pages/commands.html ("Passing Arguments" section). The missing part is that exported command files are hard coded rather than having session, etc. as variables.

Stubo exports:
    begin/session?scenario=foo&session=bar&mode=record 
rather than: 
    {% set scenario= '1234' %}
    {% set session= '5678' %}
    begin/session?scenario={{scenario[0]}}&session={{ session[0] }}&mode=record

which would allow override:
    exec/cmds?cmdFile=/static/cmds/tests/accept/smart_arg.commands&scenario=foo&session=bar

We could:
* change the export/stubs to include {{  }}, but will have to do something with the existing command files. 
* pass all command files through regEx type processing to alter them on the fly

Consider: I am not sure how templated command files work when compressed. Command files can now be JSON

**Comment by sponte** [comment]
If you do change the export, then I am sure we can easily update all existing stubs. However, regEx solution would be more flexible as it will allow to override any parameters, not just predefined ones.

Either way will be good enough for us.

**Comment by erowan** [comment]
Do you really need to make the scenario dynamic? Can you provide a use case for this. Thanks.

**Comment by sponte** [comment]
Hi @erowan, thanks for implementing. Had a quick look through the code but it seems like passing session_id is only supported on export and import of newly exported stubs. Can you confirm that this will work with existing stubs? I didn't seem to find code for this.

Thanks

**Comment by erowan** [comment]
By existing stubs do you mean existing cmdfiles? This change will enable you to provide a session on a get/export of existing stubs and on the exec/cmds of that exported cmdfile. It won't work for existing cmdfiles just new ones.

**Comment by sponte** [comment]
Thanks for your response. Would it be possible to add same functionality for already exported stubs? We have hundreds of jar files and it would be a pain to re-record them. And having some stubs with placeholders is of no value as we would like to override session if with a unique identifier on every test. 



Kind regards,
Stanislaw Wozniak

* Sent from my iPhone

**Comment by erowan** [comment]
Hello Stan

You don't have to re-record. You could automate a process to import all existing jars via exec/cmds and replace them with the output of a new export via get/export. This new code should be deployed to small-c1 today.

**Comment by johnecobo** [comment]
I would prefer for Stubo NOT to do too much MAGIC of altering existing command files on the fly. That sort of thing makes it harder for people to debug and figure out what Stubo is doing. - Explicit is better than magic.

How about a script that upgraded the existing command files without requiring a re-record?

**Comment by sponte** [comment]
We'll stick with a non-magic script then :)

Kind regards,
Stanislaw Wozniak

* Sent from my iPhone
