### ISSUE TITLE
Analytics: New "worst latency" chart

### ISSUE THREAD

**Issue by johnecobo** [Stub-O-Matic/stubo-app#44]
It is often important to see any high latency Stubo responses (excluding user added delays). These are not available on the analytics page. There is a latency chart but it is set to esclude 10% outliers to match the SLA measure.

I suggest an additional latency chart which shows the worst latency. 

Also, I question the value of the bottom row of charts: health checks, running put/stub, and running response count.

**Comment by erowan** [comment]
new latency graphed added with 6374574a32272ccbef89f2f488178103fb6f611c
