### ISSUE TITLE
random slow delays

### ISSUE THREAD

**Issue by MauMoon** [Stub-O-Matic/stubo-app#45]
I see there is currently a random delay on the stub responses.  I would like to have an additional slow delay added for performance/soak testing 

So, I can have a base delay of either a fixed time or a time with a random variance.
In addition I can have a delay on x% of responses of either a fixed time or a time with a random variance.

So, I could specify something like  -
a. 10% of responses having a delay of 5s +/- 1s
b. remaining responses having a delay of 1s +/- 0.5s

The gold plated version would be having multiple profiles -
a. 5% of responses having a delay of 30s +/- 1s
b. 15% of responses having a delay of 5s +/- 1s
b. remaining responses having a delay of 1s +/- 0.5s

**Comment by JohnFDavenport** [comment]
:+1:

Good news I think. @johnecobo or @erowan need to confirm. It was always the intention that custom delay profiles including your gold-plated version were supported by the ability to set delay_policy. If its not clear from the documentation this ought to be a documentation task.

**Comment by johnecobo** [comment]
The gold plated requirements could be met without changes to Stubo as follows:

1. Create a scenario with 3 stubs (requests and responses slightly different or they will be treated as duplicates by Stubo)
2. when loading the stubs (put/stub) give each a different delay_policy name (eg. "very_slow", "slow", and "quick") eg. put/stub?session=abc&delay_policy=very_slow ....
3. create the 3 delay policies, eg put/delay_policy? Eg. put/delay_policy?name=very_slow&delay_type=normalvariate&mean=30000&stddev=1000
4. Set your performance test to distrubute the 3 stub requests in the ration you want (5%, 15%, 80%)

Will that work for you @MauMoon ?

**Comment by MauMoon** [comment]
Thanks @johnecobo

That's really helpful.  We can use that approach for most test cases.

Where we have longer multiple step test cases and are trying to mimic
certain complex scenarios with multiple back end stubbed requests and
responses and wanting to see patterns it won't.

In the specific test case I want to replicate currently we have single
requests from clients and that generate around 40 backend requests to
various systems.    I wanted to put various time profiles on those various
backend calls and do long test (several hours) to build a profile and see
trends etc.  The main point would be to see if we can pick up the 1%
slowest transactions and possible extreme examples (those which were 'very
unlucky' and got a lot of slow responses).

Possibly an extreme test case that would be rather rare and almost nobody
would use.

**Comment by johnecobo** [comment]
@MauMoon , I understand. I suggest Stubo create a new custom delay profile. We'll call it profiled_normalvariate (or similar) and it will allow for :
a. 5% of responses having a delay of 30s +/- 1s
b. 15% of responses having a delay of 5s +/- 1s
c. remaining responses having a delay of 1s +/- 0.5s

(up to a limit of 5 or so profiles)

This could be set up similar to existing delay policies as follows:

...delay_type=profiled_normalvariate&mean=30000&stddev=1000&profile=5pct&mean=5000&stddev=1000&profile=15pct&mean=1000&stddev=500&profile=80pct

Of course much discussion can be had about the most proper way to define this as URL args, but I hope everyone gets the idea.

**Comment by guyrichardson** [comment]
For the URL, we could look at delimiters (with commas appropriately encoded as **%2C**)
**?share=5,15,80&mean=30000,5000,1000&stddev=1000,1000,500**

In wonder whether this couldn't be rationalised:
With:
* stddev defaulting to 0
* share defaulting to 100

A fixed time is 100% of responses having a stdev of +-=0s 
**?mean=300**

A random delay is 100% of responses having a stdev of +-=[x]s
**?mean=300&stddev=100**

**Comment by johnecobo** [comment]
I'd suggest finding some testers (rather than webapp developers) to try out alternative URL formats on. Its a usability thing.

**Comment by erowan** [comment]
How about the following?

Add a new weighted delay type with the following URL

```
?delay_type=weighted&delays=normalvariate,30000,1000,5;normalvariate,1000,1000,15;normalvariate,500,1000,70

you can combine different delay types if you wish
?delay_type=weighted&delays=fixed,30000,5;normalvariate,1000,1000,15;normalvariate,500,1000,70

The args to the delay type are separated by commas the last value represents the weighted pcent delimited by a semi-colon.
```

**Comment by johnecobo** [comment]
The above makes sense to me.

**Comment by erowan** [comment]
Actually use ':' as the delay separator instead of ';' which is a recommended replacement for the '&' arg separator (http://www.w3.org/TR/html401/appendix/notes.html#h-B.2.2)
