### ISSUE TITLE
Remove "End a session" link

### ISSUE THREAD

**Issue by raymondtong-ba** [Stub-O-Matic/stubo-app#46]
Hi,

Users often have to manually end active sessions in playback/record on the stubo manage page.  

Currently the user experience is rather frustrating as we have to go through the following steps:
1. Click on "Action" for a test scenario
2. Highlight "End a session" - this will bring up a link on the right, extending the page and allowing us to scroll horizontally
3. Scroll to the right until the session id appears
4. Click on the session we want to end
5. If we want to see other stubs we have to scroll back to the left again

Screenshots attached.  
![bfd4cc16-0b78-11e5-9741-0f2ff1cb811d](https://cloud.githubusercontent.com/assets/6523398/8004718/fea61962-0b79-11e5-9daa-7852fc8c09c0.png)

![bfe569d6-0b78-11e5-9466-fea381dfe837](https://cloud.githubusercontent.com/assets/6523398/8004702/dab0ee4c-0b79-11e5-9d65-65721ebcc5b6.png)

Could this please be improved?  Even something as simple as moving the list of active sessions to the left would make a huge difference to the user experience.

Thanks and regards,

Raymond

**Comment by johnecobo** [comment]
Why are sessions not being ended automatically after tests run? The GUI for this was meant only for abnormal situations.

**Comment by twinser** [comment]
When developing tests, lots of our users use the GUI to manually begin or end sessions.

Regardless, there is no point having the feature at all if it is hard to use.

**Comment by twinser** [comment]
I personally think that the drop down list is totally unnecessary. Yes you can have multiple sessions of the same scenario at once in playback or record, but I have never seen any users doing that. So surely the end all button is enough. If they are recording/playing back multiple sessions, they can use the API to end them. 

Or, if it is deemed necessary to keep the options, dynamically populate the list as follows:

Export Scenario
List Stubs                       
Delete Stubs                   
End All Active Sessions   
End Session “abcdef”      
End Session “ghijkl”         

i.e. no drop down at all

**Comment by raymondtong-ba** [comment]
I never used the "End all active sessions" command because I thought that would end all the running sessions on stubo (stopping other test runs as well), not just the scenario highlighted.  In that case, I think just having the End All Active Sessions options is fine, otherwise your solution to dynamically populate the list would work if it is necessary.

**Comment by guyrichardson** [comment]
OK, so to confirm this. 
We can remove the confusing "End a Session" option for now - subject to general usability review of the manage page.

@raymondtong-ba @twinser 
Will this affect any current users?

**Comment by twinser** [comment]
Not as far as I'm aware. Users who use the GUI are normally building tests and so tend to only run one session at a time anyway. Therefore removing the "End a Session" makes sense to me. If they are running more than one then they can use the API to end them individually.

**Comment by guyrichardson** [comment]
OK. So to confirm, the "end session" option will be removed.
