### ISSUE TITLE
Give stubs a default Time To Live

### ISSUE THREAD

**Issue by jimCresswell** [Stub-O-Matic/stubo-app#47]
Howdy,

We would appreciate it if stubs could self-destruct on the stubo server if not used for ten minutes, and if they are used then reset the TTL to ten minutes from that use. That way if we fill up a Stubo server through design or accident it will self-heal. This is related to feature #48 .

CC: @sponte @mptully @twinser

**Comment by guyrichardson** [comment]
A TTL would need to be set using a parameter, certainly - otherwise we are in danger of false deletions. 
I wonder whether UI-enhancement might add more value:

- Edit scenario
- Delete all stubs in scenario
- Deprecate scenario (activate timed removal as per TTL)
- etc.

**Comment by johnecobo** [comment]
A bit of background:
We have other users who set up several hundred scenarios for performance testing of an entire (big) application. They prefer to leave the stubs sitting around on Stubo for several days while bugs are fixed between tests. 

Any actions done in the UI must also be script-able through API and/or command files so Stubo remains a fully automated tool.

As a general rule, I prefer my tools to do what I explicitly tell them to do, nothing more, nothing less. Any magic stub deletion should be the result of users asking for it, not a default.

**Comment by erowan** [comment]
+1

**Comment by sponte** [comment]
I would like to be able to specify TTL in seconds as a parameter to any stubo call which would enable session tracking within stubo. Each call would extend TTL for number of seconds, and stubo would delete session and a stub after TTL expires.

**Comment by guyrichardson** [comment]
OK, so we agree on TTL as a potential parameter-only feature for stubs or sessions?
Potentially this is a second call to be made to an existing session/stub to expire it.

In regards the UI & API, this is taken as axiomatic.
There are several ideas about updating the UI and perhaps creating multiple persona specific-UIs. These would be best built on top of the API (as Angular/SPA)

**Comment by erowan** [comment]
My +1 was in response to @johnecobo last comment not on a TTL for scenarios. A TTL on sessions could be useful. Explicitly deleting scenarios seems ok to me.

**Comment by johnecobo** [comment]
The team are needing this by end of Nov. please.

**Comment by JohnFDavenport** [comment]
Closed as activity continued in SpectoLabs/mirage#11
