### ISSUE TITLE
Ability to overwrite ScenarioName when interacting with stubo

### ISSUE THREAD

**Issue by sponte** [Stub-O-Matic/stubo-app#52]
Extension to #39, as discussed with @johnecobo we would like to be able to override scenarioName when importing stubs (execcmds call). #39 gives us ability to change session only.

The purpose of this is to be able to use "unique" scenario name for isntance *MyTest01_testSession1234_jenkinsRun2*. This would help us in the situation where multiple users/jenkins jobs run same tests causing issues during deletion and where using separate stub urls is difficult and hard to manage.

Please let me know if you need any more details.

**Comment by guyrichardson** [comment]
OK, so the scenario names are set in the command file and you want to override it in the API call?

**Comment by sponte** [comment]
Yes, I want to be able to dynamically generate scenario name to avoid clashes with multiple executions at the same time

**Comment by guyrichardson** [comment]
OK. 

@johnecobo @erowan @sponte 

I note that the commandfile format has been updated to use YAML in 0.6.2
http://stubo-app.readthedocs.org/en/latest/pages/commands.html

I'm reading up on this now.
Does this solve the present problem or another issue?

**Comment by erowan** [comment]
Scenario names are fixed not overridable in both formats. Currently you can only override the session name.

**Comment by guyrichardson** [comment]
So to confirm the requirement. 
On export of recorded stubs, the generated command file should be setup to allow overriding of the scenario name.

**Comment by sponte** [comment]
Correct, exactly like #39 but for scenarioName

**Comment by guyrichardson** [comment]
Thinking about this is a different way...

Would the facility to clone a scenario with a new scenario and session name be useful?
This would remove the requirement to export and then reimport stub files.

**Comment by johnecobo** [comment]
Stubo is designed to only hold stub data (scenarios) on a temporary basis - while a test runs. As it is not the master stub store, it would be unlikely that the scenario you want to clone is loaded in Stubo.

We did consider Stubo as the master stub data warehouse. but that would separate the stubs from the tests they support which seemed like a bad idea - especially when multiple versions of the tests and stubs is considered.

**Comment by guyrichardson** [comment]
OK, fair enough - thank you for the context.

**Comment by rusenask** [comment]
@johnecobo could you share with us your testing workflow, for example how do you upload stubs, where do you store command files? Maybe Jenkins could modify command files?

**Comment by JohnFDavenport** [comment]
That information is on the project wiki. I need to get you access to that as there is too much for me to bundle into PDF files for you. Also, it might be worth @rusenask bringing you in to shadow a couple of people in the test teams so you can see the process from their point of view.

**Comment by sponte** [comment]
Hi, any updates on this issue?

**Comment by rusenask** [comment]
@sponte - I have been thinking about this feature and I can't find a logical and right way to do it. When you export scenario - you expect to get the same scenario after importing it. Additional function just to change a text file seems unnecessary and probably belongs somewhere else (api user).
Have you tried using Jenkins functionality? For example you can modify test job to use unix "sed" command on that commands file and change scenario name to append Jenkins build number to it and every test job would have unique number. I have used that build number value to build unique RPMs, no problems with versions after that.

**Comment by sponte** [comment]
We have all our stubs in jar files which are stored in subversion. In order for me to change values in commands file, i'd have to checkout the file, expand the archive, update, commit and import stub.

Original request for this was #39 which was implemented but for sessionName. If we do the same but for scenarioName it will allow us to override this though the url when we import the stub. Then we'll be able to send "dynamic" scenario names from Jenkins.

**Comment by rusenask** [comment]
okay, I will have a look at it tomorrow.

**Comment by sponte** [comment]
Thanks

**Comment by rusenask** [comment]
What do you think about additional API call to change existing scenario name? This way it would be explicit function for all users. You could modify your Jenkins jobs to automatically rename scenarios after import.

**Comment by sponte** [comment]
That would be awesome. And neater as we wouldn't have to redownload all the stubs. 

Kind regards,
Stanislaw Wozniak

* Sent from my iPhone
