### ISSUE TITLE
Date rolling requirement

### ISSUE THREAD

**Issue by guyrichardson** [Stub-O-Matic/stubo-app#55]
Suppose we have multiple occurances of a tag "ArrivalDate" in response (or matcher) and the date present in each of the tag is different. For example :

<ArrivalDate>2015-06-08</ArrivalDate> 
blah blah 
<ArrivalDate>2015-09-08</ArrivalDate> 
blah blah 
<ArrivalDate>2015-12-08</ArrivalDate> 

Currently the extractor is using the first value it finds from the XPATH and replacing all occurrences with it, as follows :

<ArrivalDate>{{raw roll_date('2015-06-08', as_date(recorded_on), as_date(played_on))}}</ArrivalDate> 
blah blah 
<ArrivalDate>{{raw roll_date('2015-06-08', as_date(recorded_on), as_date(played_on))}}</ArrivalDate> 
blah blah 
<ArrivalDate>{{raw roll_date('2015-06-08', as_date(recorded_on), as_date(played_on))}}</ArrivalDate>

Requirement is that date roll should be like as follows (date rolling should be based on the date present in each of the tag):

<ArrivalDate>{{raw roll_date('2015-06-08', as_date(recorded_on), as_date(played_on))}}</ArrivalDate> 
blah blah 
<ArrivalDate>{{raw roll_date('2015-09-08', as_date(recorded_on), as_date(played_on))}}</ArrivalDate> 
blah blah 
<ArrivalDate>{{raw roll_date('2015-12-08', as_date(recorded_on), as_date(played_on))}}</ArrivalDate>

**Comment by JohnFDavenport** [comment]
I think this ought to be tagged as a bug rather than a feature and should be urgent.

**Comment by JohnFDavenport** [comment]
:+1:
