### ISSUE TITLE
response date rolling requirement 

### ISSUE THREAD

**Issue by roopeshpraj** [Stub-O-Matic/stubo-app#82]
There is a response date rolling requirement in which date of format "YYMMDD" appearing in plain text need to be rolled forward : 
Example string - 'KER+BA+322+1408131745+LHR+CDG

a) BA-might vary as AA, US, etc 
b) 322 - might vary as 55, 101 , 1435, etc - [0-9]{2,3,4}
c) 1745+LHR+CDG may also vary 0000+XXX+XXX
d) recorded date 140813 (YYMMDD) should be rolled to play back date.

If the date delta is 2 days, then the rolled response should be
'KER+BA+322+1408151745+LHR+CDG  => 140813 rolled forward to 140815

Examples : 
case 1:KER+BA+9459+1504021500+CMN+LHR
case 2:KER+BA+1327+1504061215+NCL+LHR
case 3:KER+BA+1389+1504020955+MAN+LHR
case 4:KER+BA+335+1505271405+ORY+LHR
case 5:KER+BA+335+1505291405+ORY+LHR+1505291535+A
             KER+BA+444+1505292015+LHR+AMS+2905152225+T 

case 5 differs from others as it has two segments. (response file can have 1 or 2 occurances of XXX+XX+[0-9]{2,3,4}+1505290000+XXX+XXX and therefore should roll both the dates.)

Current date rolling expects date to be enclosed in an XML tag and also the date format "YYMMDD" is not supported. 

Because of this requirement a number of test cases of ba.com is failing. Appreciate a speedy solution.

**Comment by rusenask** [comment]
Thanks Roopesh, looking into this. So there can be either one or two dates? I will try to create a general solution for string mangling so it fits into stubo.

**Comment by rusenask** [comment]
Also, can you explain this more "Because of this requirement a number of test cases of ba.com is failing. Appreciate a speedy solution." ? What was the solution before when these test cases were not failing? 

Please provide more information about request (what is being matched?). Also, have you looked at http://stubo-app.readthedocs.org/en/latest/pages/advanced.html#templated-responses and thought whether it could do the job?

**Comment by roopeshpraj** [comment]
Hi Karolis, Sorry for the late reply. Yes there can be either one or two dates.
These are new test cases so there was no other solution used. 
Request / matcher can be anything "helloworld", since what we are looking for is response date rolling.
Templated responses I tried, but will not work. In fact the example test case that I share uses templated response.

**Comment by guyrichardson** [comment]
Template provided to BA
