### ISSUE TITLE
Performance degradation in 0.6.5-476 and 0.6.6-483 releases

### ISSUE THREAD

**Issue by roopeshpraj** [Stub-O-Matic/stubo-app#95]
Compared to 0.6.4-469 release, there is considerable performance degradation in both 0.6.5-476 and 0.6.6-483 releases. Release wise performance test results is as follows :

1) 0.6.4-469 - Request/sec is consistently over 1000, as expected
Build #784 
cnt: 196955, avg t: 36 ms, max t: 1306 ms, min t: 5 ms, result codes: {200=196955}, failures: 0, cnt by time: [0.0 s - 0.5 s = 196679, 0.5 s - 1.0 s = 252, 1.0 s - 1.5 s = 24]
Description set: Req/sec: 1089

2) 0.6.5-476
Build #783
cnt: 89217, avg t: 83 ms, max t: 2122 ms, min t: 5 ms, result codes: {200=89217}, failures: 0, cnt by time: [0.0 s - 0.5 s = 89043, 0.5 s - 1.0 s = 126, 1.0 s - 1.5 s = 45, 2.0 s - 2.5 s = 3]
Description set: Req/sec: 493

3) 0.6.6-483 ~ Request/sec is consistently ~500
Build #781
cnt: 96064, avg t: 77 ms, max t: 644 ms, min t: 5 ms, result codes: {200=96064}, failures: 0, cnt by time: [0.0 s - 0.5 s = 96053, 0.5 s - 1.0 s = 11]
Description set: Req/sec: 533

Yappi profiling was done and the result provided for further investigation.

**Comment by rusenask** [comment]
Solved with https://github.com/Stub-O-Matic/stubo-app/pull/97
